# Generated by Django 5.2 on 2025-04-11 11:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="temp")),
                (
                    "color_default",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_null",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "color_rgb",
                    colorfield.fields.ColorField(
                        default="rgb(255, 255, 255)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_rgba",
                    colorfield.fields.ColorField(
                        default="rgba(255, 255, 255, 1)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_choices",
                    colorfield.fields.ColorField(
                        blank=True,
                        choices=[("#FFFFFF", "white"), ("#000000", "black")],
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_samples",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=[("#FFFFFF", "white"), ("#000000", "black")],
                    ),
                ),
                (
                    "color_image",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_default",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="#FF0000",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_hexa",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_rgb",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_rgba",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
            ],
        ),
    ]
