# Generated by Django 5.2 on 2025-04-30 09:13

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="temp")),
                (
                    "color_default",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_null",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "color_rgb",
                    colorfield.fields.ColorField(
                        default="rgb(255, 255, 255)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_rgba",
                    colorfield.fields.ColorField(
                        default="rgba(255, 255, 255, 1)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_choices",
                    colorfield.fields.ColorField(
                        blank=True,
                        choices=[
                            ("#067bc2", "dark blue"),
                            ("#84bcda", "light blue"),
                            ("#80e377", "green"),
                            ("#ecc30b", "yellow"),
                            ("#f37748", "orange"),
                            ("#d56062", "red"),
                            ("#ffffff", "white"),
                            ("#000000", "black"),
                        ],
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_samples",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#067BC2", "dark blue"),
                            ("#84BCDA", "light blue"),
                            ("#80E377", "green"),
                            ("#ECC30B", "yellow"),
                            ("#F37748", "orange"),
                            ("#D56062", "red"),
                            ("#FFFFFF", "white"),
                            ("#000000", "black"),
                        ],
                    ),
                ),
                (
                    "color_image",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_default",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="#FF0000",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_hexa",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_rgb",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_rgba",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Palette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="PaletteColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "color_choices",
                    colorfield.fields.ColorField(
                        choices=[
                            ("#067bc2", "dark blue"),
                            ("#84bcda", "light blue"),
                            ("#80e377", "green"),
                            ("#ecc30b", "yellow"),
                            ("#f37748", "orange"),
                            ("#d56062", "red"),
                            ("#ffffff", "white"),
                            ("#000000", "black"),
                        ],
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_rgb",
                    colorfield.fields.ColorField(
                        default="rgb(255, 255, 255)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "palette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colorfield_example.palette",
                    ),
                ),
            ],
        ),
    ]
