# Generated by Django 5.2 on 2025-05-03 10:12

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models

from ..models import COLOR_PALETTE


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_default",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_ro",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_null",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "color_rgb",
                    colorfield.fields.ColorField(
                        default="rgb(255, 255, 255)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_rgba",
                    colorfield.fields.ColorField(
                        default="rgba(255, 255, 255, 1)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_choices",
                    colorfield.fields.ColorField(
                        blank=True,
                        choices=COLOR_PALETTE,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_samples",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        image_field=None,
                        max_length=25,
                        samples=COLOR_PALETTE,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="temp")),
                (
                    "color_image_hex",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        editable=False,
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_hexa",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        editable=False,
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_rgb",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        editable=False,
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_image_rgba",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        editable=False,
                        image_field="image",
                        max_length=25,
                        samples=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Palette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="PaletteColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "color_choices",
                    colorfield.fields.ColorField(
                        choices=COLOR_PALETTE,
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "color_rgb",
                    colorfield.fields.ColorField(
                        default="rgb(255, 255, 255)",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "palette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_example.palette",
                    ),
                ),
            ],
        ),
    ]
